export const DB_ACTION_START = 'SAVE_NOTE_START';
export const DB_ACTION_SUCCESS = 'SAVE_NOTE_SUCCESS';
export const DB_ACTION_FAILED = 'SAVE_NOTE_FAILED';

export const RESET_NOTE_STATE_DEFAULT = 'RESET_NOTE_STATE_DEFAULT';

export const AUTH_USER_START = 'AUTH_USER_START';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILED = 'AUTH_USER_FAILED';
export const AUTH_ERROR_RESET = 'AUTH_ERROR_RESET';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';

export const SET_GLOBAL_MESSAGE = 'SET_GLOBAL_MESSAGE';
export const UNSET_GLOBAL_MESSAGE = 'UNSET_GLOBAL_MESSAGE';

export const FETCH_ALL_NOTES_TITLE = 'FETCH_ALL_NOTES_TITLE';
export const SAVE_NOTES_LIST = 'SAVE_NOTES_LIST';
export const FETCH_NOTES_TITLES_FAILED = 'FETCH_NOTES_TITLES_FAILED';
export const FETCH_NOTES_TITLE_START = 'FETCH_NOTES_TITLE_START';
export const FETCH_MORE_NOTES_START = 'FETCH_MORE_NOTES_START';

export const UPDATE_NOTE_REDUX = 'UPDATE_NOTE_TITLES';
export const DELETE_NOTE_REDUX = 'DELETE_NOTE';
export const SAVE_NOTE_REDUX = 'SAVE_NOTE_REDUX';
export const CLEAR_NOTE_REDUX = 'CLEAR_NOTE_REDUX';