export const APPEND_ITEM = 'APPEND_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_MULTIPLE_ITEMS = 'DELETE_MULTIPLE_ITEMS';
export const CHANGE_STRIKE_STATE = 'CHANGE_STRIKE_STATE';
export const SAVE_CHANGES = 'SAVE_CHANGES';

export const SET_ERROR = 'SET_ERROR';
export const UNSET_ERROR = 'UNSET_ERROR';

export const SAVE_TO_DB_START = 'SAVE_TO_DB_START';
export const SAVE_TO_DB_SUCCESS = 'SAVE_TO_DB_SUCCESS';
export const SAVE_TO_DB_FAILED = 'SAVE_TO_DB_FAILED';

export const FETCH_FROM_DB_START = 'FETCH_FROM_DB_START';
export const FETCH_FROM_DB_SUCCESS = 'FETCH_FROM_DB_SUCCESS';
export const FETCH_FROM_DB_FAILED = 'FETCH_FROM_DB_FAILED';