export const APPEND_ITEM = 'APPEND_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_MULTIPLE_ITEMS = 'DELETE_MULTIPLE_ITEMS';
export const CHANGE_STRIKE_STATE = 'CHANGE_STRIKE_STATE';
export const SAVE_CHANGES = 'SAVE_CHANGES';

export const SAVE_TO_DB_START = 'SAVE_TO_DB_START';